---
Name: codem-domain-validation
---
Codem\DomainValidation\AbstractDomainValidator:
    ttl: 0
Codem\DomainValidation\MxValidatedEmailField:
    extensions:
        - 'Codem\DomainValidation\FieldExtension'
    dns_clients:
        - 'Codem\DomainValidation\CloudflareDnsOverHttps'
Codem\DomainValidation\ValidatedDomainField:
    extensions:
        - 'Codem\DomainValidation\FieldExtension'
    dns_checks:
        - A
    dns_clients:
        - 'Codem\DomainValidation\CloudflareDnsOverHttps'
Codem\DomainValidation\DomainLookupForm:
    dns_checks:
        - A
    dns_client: 'Codem\DomainValidation\CloudflareDnsOverHttps'
