---
Name: codem-domain-validation
---
Codem\DomainValidation\MxValidatedEmailField:
    extensions:
        - 'Codem\DomainValidation\FieldExtension'
    dns_checks:
        - MX
    domain_validators:
        - 'Codem\DomainValidation\CloudflareDnsOverHttps'
Codem\DomainValidation\ValidatedDomainField:
    extensions:
        - 'Codem\DomainValidation\FieldExtension'
    dns_checks:
        - A
        - AAAA
    domain_validators:
        - 'Codem\DomainValidation\CloudflareDnsOverHttps'